services:
    _defaults:
        autowire: true
        autoconfigure: true

    GeodisBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Tests}'

    GeodisBundle\Manager\GeodisJsonApi:
        autowire: true
        autoconfigure: true
        public: false
        lazy: true