services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $baseUri: '%env(GEODIS_API_BASE_URI)%'
            $apiKey:  '%env(GEODIS_API_KEY)%'

    GeodisBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Tests}'

    GeodisBundle\Repository\GeodisLoggerRepository:
        factory: ['@doctrine', getRepository]
        arguments: [GeodisBundle\Entity\GeodisLogger]

