services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $apiKey:  '%env(GEODIS_API_KEY)%'

    GeodisBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Tests}'

    GeodisBundle\Manager\GeodisJsonApi:
        autowire: true
        autoconfigure: true
        public: false
        lazy: true