services:
    geodis.rest_api:
        class: GeodisBundle\Manager\GeodisJsonApi
        arguments: ['@doctrine.orm.entity_manager']

    geodis.exceptionlistener:
        class: GeodisBundle\Event\ExceptionListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: monolog.logger, channel: exactAPI }
